name: Publish Docker Image (Frontend)

on: 
    push:
    workflow_dispatch:

jobs:
    build-publish:
        runs-on: ubuntu-latest
        name: Build Frontend Docker Image
        steps:
            - name: Clone repository
              uses: actions/checkout@v4

            - name: Setup docker buildx
              uses: docker/setup-buildx-action@v3.7.1

            - name: Fetch app version
              working-directory: frontend
              id: fetch_version
              run: |
                VERSION=$(jq -r '.version' package.json)
                echo "version=${VERSION}" >> $GITHUB_OUTPUT

            - name: Login to GHCR
              uses: docker/login-action@v3.3.0
              with:
                registry: ghcr.io
                username: vlsts
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build docker image
              uses: docker/build-push-action@v6.10.0
              with:
                file: Dockerfile
                push: true
                labels: |
                  org.opencontainers.image.source=https://github.com/vlsts/countryname
                  org.opencontainers.image.url=https://github.com/vlsts/countryname
                  org.opencontainers.image.title="Countryname frontend website"
                  org.opencontainers.image.description="Frontend for the countryname project."
                tags: ghcr.io/vlsts/countryname:latest,ghcr.io/vlsts/countryname:${{ steps.fetch_version.outputs.version }}